package kz.talgat.models

import java.time.LocalDate

case class Person(id: Int,
                  nationalIdentifier: Option[String],
                  firstName: String,
                  middleName: Option[String],
                  lastName: String,
                  formerName: Option[String],
                  nickName: Option[String],
                  email: String,
                  workPhone: Option[String],
                  homePhone: Option[String],
                  mobilePhone: Option[String],
                  prefixCd: Option[Int],
                  suffixCd: Option[Int],
                  dateOfBirth: Option[LocalDate],
                  dateOfDeath: Option[LocalDate],
                  genderCd: Option[Int],
                  maritalStatusCd: Option[Int],
                  ethnicityCd: Option[Int],
                  citizenshipCountryCd: Option[Int],
                  militaryStatusCd: Option[Int],
                  lastMilitarySeparation: Option[LocalDate],
                  isTobaccoUser: Option[Boolean],
                  isHandicapped: Option[Boolean],
                  isSubstanceAbuse: Option[Boolean],
                  disabilityCd: Option[Int],
                  workflowLogId: Option[Int],
                  statusCd: Int,
                  signatureId: Option[Int],
                  personalEmail: Option[String],
                  additionalPhoneNumber: Option[String],
                  nationalIdentifierEncrypted: Boolean,
                  pronounsCd: Option[Int])
